// User & Auth Models
export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  organizationId: string;
  organizationName: string;
}

export type UserRole = 'Admin' | 'TeamLead' | 'Developer' | 'Viewer';

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  organizationName: string;
  organizationSlug: string;
}

export interface AuthResponse {
  token: string;
  refreshToken: string;
  expiresAt: string;
  user: User;
}

// Project Models
export interface Project {
  id: string;
  name: string;
  slug: string;
  description: string;
  environmentCount: number;
  scenarioCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface ProjectDetail extends Project {
  environments: Environment[];
  collections: ApiCollection[];
  scenarios: ScenarioSummary[];
}

export interface Environment {
  id: string;
  name: string;
  baseUrl: string;
  isDefault: boolean;
}

export interface ApiCollection {
  id: string;
  name: string;
  endpointCount: number;
}

// Scenario Models
export interface ScenarioSummary {
  id: string;
  name: string;
  executionType: ExecutionType;
}

export interface Scenario {
  id: string;
  name: string;
  description: string;
  executionType: ExecutionType;
  loadModel: LoadModel;
  requestDistribution: RequestDistribution;
  minThinkTimeMs: number;
  maxThinkTimeMs: number;
  stages: ScenarioStage[];
  requests: ScenarioRequest[];
  thresholds: ScenarioThreshold[];
  createdAt: string;
  updatedAt: string;
}

export type ExecutionType = 'Load' | 'Ramp' | 'Spike' | 'Stress' | 'Soak';
export type LoadModel = 'VirtualUsers' | 'ConstantArrivalRate';
export type RequestDistribution = 'Weighted' | 'Sequential' | 'Random';
export type RampStrategy = 'Linear' | 'Exponential' | 'Step' | 'Immediate';

export interface ScenarioStage {
  id: string;
  name: string;
  durationSeconds: number;
  targetVUs: number;
  targetRPS?: number;
  rampStrategy: RampStrategy;
  orderIndex: number;
}

export interface ScenarioRequest {
  id: string;
  endpointId: string;
  endpointName: string;
  method: string;
  url: string;
  weight: number;
}

export interface ScenarioThreshold {
  id: string;
  metric: ThresholdMetric;
  operator: ThresholdOperator;
  value: number;
}

export type ThresholdMetric = 'P50Latency' | 'P90Latency' | 'P95Latency' | 'P99Latency' | 'AvgLatency' | 'MaxLatency' | 'RPS' | 'ErrorRate';
export type ThresholdOperator = 'LessThan' | 'LessThanOrEqual' | 'GreaterThan' | 'GreaterThanOrEqual' | 'Equal';

// Test Run Models
export interface TestRun {
  id: string;
  runNumber: string;
  scenarioId: string;
  scenarioName: string;
  environmentName: string;
  status: RunStatus;
  result: RunResult;
  trigger: RunTrigger;
  triggeredBy: string;
  startedAt: string;
  completedAt?: string;
  durationSeconds?: number;
  isBaseline: boolean;
  createdAt: string;
}

export type RunStatus = 'Pending' | 'Queued' | 'Initializing' | 'Running' | 'Stopping' | 'Completed' | 'Failed' | 'Cancelled';
export type RunResult = 'Pass' | 'Fail' | 'Error';
export type RunTrigger = 'Manual' | 'Scheduled' | 'API' | 'CI';

export interface RunMetrics {
  timestamp: string;
  totalRequests: number;
  failedRequests: number;
  rps: number;
  avgLatencyMs: number;
  p50LatencyMs: number;
  p95LatencyMs: number;
  p99LatencyMs: number;
  activeVUs: number;
}

export interface ThresholdResult {
  metric: ThresholdMetric;
  operator: ThresholdOperator;
  expectedValue: number;
  actualValue: number;
  passed: boolean;
}

// API Response
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  errors?: { [key: string]: string[] };
}

export interface PaginatedResponse<T> {
  items: T[];
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
}

// ──────────────────────────────────────────────────
// Coverage-Focused Test Suite Models
// ──────────────────────────────────────────────────

export type TestSeverity = 'P0' | 'P1' | 'P2';
export type CoverageCategory = 'Smoke' | 'Validation' | 'Boundary' | 'Negative' | 'Contract' | 'StateAwareCRUD';
export type GeneratedRunStatus = 'Pending' | 'Running' | 'Passed' | 'Failed' | 'Partial' | 'Cancelled';

export interface GeneratedTestCase {
  id: string;
  name: string;
  severity: TestSeverity;
  method: string;
  path: string;
  coverageCategory: CoverageCategory;
  expectedStatusCodes: number[];
  autoGenerated: boolean;
  needsReview: boolean;
  isActive: boolean;
  createdAt: string;
}

export interface GeneratedTestCaseDetail extends GeneratedTestCase {
  payloadJson?: string;
  assertionsJson?: string;
  setupJson?: string;
  teardownJson?: string;
  dependenciesJson?: string;
  updatedAt: string;
}

export interface GenerationSummary {
  collectionId: string;
  collectionName: string;
  totalTestsGenerated: number;
  smokeTests: number;
  validationTests: number;
  boundaryTests: number;
  negativeTests: number;
  contractTests: number;
  crudTests: number;
  p0Tests: number;
  p1Tests: number;
  p2Tests: number;
  endpointsCovered: number;
  seed: number;
}

export interface CoverageSummary {
  collectionId: string;
  totalTests: number;
  smokeTests: number;
  validationTests: number;
  boundaryTests: number;
  negativeTests: number;
  contractTests: number;
  crudTests: number;
  p0Tests: number;
  p1Tests: number;
  p2Tests: number;
  autoGeneratedTests: number;
  manualTests: number;
  needsReviewCount: number;
  endpointsCovered: number;
}

export interface GeneratedTestRun {
  id: string;
  status: GeneratedRunStatus;
  totalTests: number;
  passedTests: number;
  failedTests: number;
  skippedTests: number;
  passRate: number;
  durationSeconds: number;
  createdAt: string;
  startedAt?: string;
  completedAt?: string;
}

export interface GeneratedTestRunDetail extends GeneratedTestRun {
  executions: TestExecution[];
}

export interface TestExecution {
  id: string;
  testCaseId: string;
  status: string;
  responseStatusCode?: number;
  durationMs: number;
  correlationId?: string;
  errorMessage?: string;
  retryCount: number;
  requestJson?: string;
  responseJson?: string;
  assertionResultsJson?: string;
}

export interface ExecuteTestSuiteRequest {
  environmentId: string;
  authToken?: string;
  description?: string;
  severityFilter?: string;
  categoryFilter?: string;
}

export interface ExecuteTestSuiteResponse {
  runId: string;
  status: string;
  totalTests: number;
  passedTests: number;
  failedTests: number;
  skippedTests: number;
  passRate: number;
  durationSeconds: number;
}

export interface ImportOpenApiRequest {
  openApiContent: string;
  fileName?: string;
}

export interface ImportOpenApiResponse {
  collectionId: string;
  collectionName: string;
  endpointCount: number;
  title: string;
  version: string;
  servers: string[];
}

export interface GenerateTestSuiteRequest {
  openApiContent: string;
  seed?: number;
  testDataPrefix?: string;
  generateSmoke?: boolean;
  generateValidation?: boolean;
  generateBoundary?: boolean;
  generateNegative?: boolean;
  generateContract?: boolean;
  generateCrud?: boolean;
}

// ──────────────────────────────────────────────────
// SLM Models
// ──────────────────────────────────────────────────

export interface ExtractRulesRequest {
  inputText: string;
}

export interface ExtractRulesResponse {
  rulesExtracted: number;
  testsGenerated: number;
  confidence: number;
  message: string;
  rules: ExtractedRule[];
}

export interface ExtractedRule {
  type: string;
  description: string;
  leftField?: string;
  rightField?: string;
  operator?: string;
}

