using LoadForge.TestGeneration.Models;

namespace LoadForge.TestGeneration.Generation;

/// <summary>
/// Module D: TestAssembler
/// Orchestrates the full deterministic test suite generation pipeline.
/// OpenAPI Spec → Parser → ValidPayloadBuilder → MutationEngine → TestCaseDefinitions
/// 
/// Produces tests for each endpoint covering:
///   - Smoke (P0): Valid request → 2xx → schema valid
///   - Validation (P1): Missing required, wrong type, invalid enum, extra properties
///   - Boundary (P2): String/numeric/array boundary values
///   - Negative (P1): Auth failures (401, 403), bad IDs (400, 404)
///   - Contract (P1): Response schema validation, required headers
///   - State-Aware CRUD (P0): POST → GET → PUT/PATCH → GET → DELETE → GET(404)
/// </summary>
public class TestAssembler
{
    private readonly ValidPayloadBuilder _payloadBuilder;
    private readonly MutationEngine _mutationEngine;
    private readonly TestGenerationConfig _config;

    public TestAssembler(TestGenerationConfig? config = null)
    {
        _config = config ?? new TestGenerationConfig();
        _payloadBuilder = new ValidPayloadBuilder(_config.Seed, _config.TestDataPrefix);
        _mutationEngine = new MutationEngine(_payloadBuilder);
    }

    /// <summary>
    /// Generate a complete deterministic test suite from a parsed OpenAPI specification.
    /// </summary>
    public List<TestCaseDefinition> GenerateTestSuite(ParsedApiSpec spec)
    {
        var tests = new List<TestCaseDefinition>();
        var counter = 0;

        foreach (var endpoint in spec.Endpoints)
        {
            if (endpoint.IsDeprecated) continue;

            if (_config.GenerateSmokeTests)
                tests.AddRange(GenerateSmokeTests(endpoint, ref counter));

            if (_config.GenerateValidationTests && endpoint.RequestBody != null)
                tests.AddRange(GenerateValidationTests(endpoint, ref counter));

            if (_config.GenerateBoundaryTests && endpoint.RequestBody != null)
                tests.AddRange(GenerateBoundaryTests(endpoint, ref counter));

            if (_config.GenerateNegativeTests)
                tests.AddRange(GenerateNegativeTests(endpoint, ref counter));

            if (_config.GenerateContractTests)
                tests.AddRange(GenerateContractTests(endpoint, ref counter));
        }

        if (_config.GenerateCrudTests)
            tests.AddRange(GenerateCrudSequences(spec, ref counter));

        return tests;
    }

    // ──────────────────────────────────────────────────
    // SMOKE TESTS (P0)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateSmokeTests(ParsedEndpoint endpoint, ref int counter)
    {
        var tests = new List<TestCaseDefinition>();
        counter++;

        var test = new TestCaseDefinition
        {
            Id = $"SMOKE-{counter:D4}",
            Name = $"[Smoke] {endpoint.Method} {endpoint.Path} - Valid request returns success",
            Severity = "P0",
            Method = endpoint.Method,
            Path = endpoint.Path,
            CoverageCategory = "Smoke",
            ExpectedStatusCodes = GetSuccessStatusCodes(endpoint),
            AutoGenerated = true,
            NeedsReview = false,
            Description = $"Smoke test: Valid {endpoint.Method} request to {endpoint.Path} should return 2xx"
        };

        // Build valid payload if endpoint has a request body
        if (endpoint.RequestBody != null)
        {
            test.Payload = _payloadBuilder.BuildPayload(endpoint.RequestBody);
        }

        // Build path parameters
        test.PathParams = BuildPathParams(endpoint);

        // Add response schema assertion
        test.Assertions.Add(new TestAssertion
        {
            Type = "status_code",
            Expected = string.Join(",", test.ExpectedStatusCodes),
            Operator = "in"
        });

        // Add schema validation assertion if response schema exists
        if (endpoint.Responses.TryGetValue("200", out var responseSchema) ||
            endpoint.Responses.TryGetValue("201", out responseSchema))
        {
            test.Assertions.Add(new TestAssertion
            {
                Type = "schema_valid",
                Expected = "true",
                Operator = "equals"
            });

            // Assert required fields exist in response
            foreach (var requiredField in responseSchema.Required)
            {
                test.Assertions.Add(new TestAssertion
                {
                    Type = "jsonpath_exists",
                    Expression = $"$.{requiredField}",
                    Operator = "exists"
                });
            }
        }

        tests.Add(test);
        return tests;
    }

    // ──────────────────────────────────────────────────
    // VALIDATION TESTS (P1)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateValidationTests(ParsedEndpoint endpoint, ref int counter)
    {
        var tests = new List<TestCaseDefinition>();
        if (endpoint.RequestBody == null) return tests;

        var validPayload = _payloadBuilder.BuildPayload(endpoint.RequestBody);

        // Missing required fields
        foreach (var mutation in _mutationEngine.GenerateMissingRequiredFieldMutations(endpoint.RequestBody, validPayload))
        {
            counter++;
            tests.Add(CreateMutationTest(
                $"VAL-{counter:D4}",
                "Validation",
                "P1",
                endpoint,
                mutation
            ));
        }

        // Wrong type
        foreach (var mutation in _mutationEngine.GenerateWrongTypeMutations(endpoint.RequestBody, validPayload))
        {
            counter++;
            tests.Add(CreateMutationTest(
                $"VAL-{counter:D4}",
                "Validation",
                "P1",
                endpoint,
                mutation
            ));
        }

        // Invalid enum
        foreach (var mutation in _mutationEngine.GenerateInvalidEnumMutations(endpoint.RequestBody, validPayload))
        {
            counter++;
            tests.Add(CreateMutationTest(
                $"VAL-{counter:D4}",
                "Validation",
                "P1",
                endpoint,
                mutation
            ));
        }

        // Additional property
        var additionalProp = _mutationEngine.GenerateAdditionalPropertyMutation(endpoint.RequestBody, validPayload);
        if (additionalProp != null)
        {
            counter++;
            tests.Add(CreateMutationTest(
                $"VAL-{counter:D4}",
                "Validation",
                "P1",
                endpoint,
                additionalProp
            ));
        }

        return tests;
    }

    // ──────────────────────────────────────────────────
    // BOUNDARY TESTS (P2)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateBoundaryTests(ParsedEndpoint endpoint, ref int counter)
    {
        var tests = new List<TestCaseDefinition>();
        if (endpoint.RequestBody == null) return tests;

        var validPayload = _payloadBuilder.BuildPayload(endpoint.RequestBody);

        // String boundaries
        foreach (var mutation in _mutationEngine.GenerateStringBoundaryMutations(endpoint.RequestBody, validPayload))
        {
            counter++;
            var test = CreateMutationTest(
                $"BND-{counter:D4}",
                "Boundary",
                "P2",
                endpoint,
                mutation
            );
            tests.Add(test);
        }

        // Numeric boundaries
        foreach (var mutation in _mutationEngine.GenerateNumericBoundaryMutations(endpoint.RequestBody, validPayload))
        {
            counter++;
            tests.Add(CreateMutationTest(
                $"BND-{counter:D4}",
                "Boundary",
                "P2",
                endpoint,
                mutation
            ));
        }

        // Array boundaries
        foreach (var mutation in _mutationEngine.GenerateArrayBoundaryMutations(endpoint.RequestBody, validPayload))
        {
            counter++;
            tests.Add(CreateMutationTest(
                $"BND-{counter:D4}",
                "Boundary",
                "P2",
                endpoint,
                mutation
            ));
        }

        return tests;
    }

    // ──────────────────────────────────────────────────
    // NEGATIVE TESTS (P1)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateNegativeTests(ParsedEndpoint endpoint, ref int counter)
    {
        var tests = new List<TestCaseDefinition>();

        // Auth negative tests: ONLY generate if the endpoint has security requirements defined
        if (endpoint.Security.Count > 0)
        {
            // No auth token → 401
            counter++;
            tests.Add(new TestCaseDefinition
            {
                Id = $"NEG-{counter:D4}",
                Name = $"[Negative] {endpoint.Method} {endpoint.Path} - No auth token → 401",
                Severity = "P1",
                Method = endpoint.Method,
                Path = endpoint.Path,
                CoverageCategory = "Negative",
                ExpectedStatusCodes = [401],
                Headers = new Dictionary<string, string>(), // Explicitly no Authorization header
                PathParams = BuildPathParams(endpoint),
                Assertions = new List<TestAssertion>
                {
                    new() { Type = "status_code", Expected = "401", Operator = "equals" }
                },
                AutoGenerated = true,
                Description = "No authentication token should result in 401 Unauthorized"
            });

            // Invalid auth token → 401
            counter++;
            tests.Add(new TestCaseDefinition
            {
                Id = $"NEG-{counter:D4}",
                Name = $"[Negative] {endpoint.Method} {endpoint.Path} - Invalid auth token → 401",
                Severity = "P1",
                Method = endpoint.Method,
                Path = endpoint.Path,
                CoverageCategory = "Negative",
                ExpectedStatusCodes = [401],
                Headers = new Dictionary<string, string>
                {
                    ["Authorization"] = "Bearer invalid_token_loadforge_test"
                },
                PathParams = BuildPathParams(endpoint),
                Assertions = new List<TestAssertion>
                {
                    new() { Type = "status_code", Expected = "401", Operator = "equals" }
                },
                AutoGenerated = true,
                Description = "Invalid authentication token should result in 401 Unauthorized"
            });
        }

        // Invalid ID format → 400 (for endpoints with path params that look like IDs)
        var idParams = endpoint.Parameters
            .Where(p => p.In == "path" && IsIdParameter(p))
            .ToList();

        foreach (var idParam in idParams)
        {
            counter++;
            var invalidPathParams = BuildPathParams(endpoint);
            if (invalidPathParams != null)
                invalidPathParams[idParam.Name] = "not-a-valid-id-format";

            tests.Add(new TestCaseDefinition
            {
                Id = $"NEG-{counter:D4}",
                Name = $"[Negative] {endpoint.Method} {endpoint.Path} - Invalid {idParam.Name} format → 400",
                Severity = "P1",
                Method = endpoint.Method,
                Path = endpoint.Path,
                CoverageCategory = "Negative",
                ExpectedStatusCodes = [400],
                PathParams = invalidPathParams,
                Assertions = new List<TestAssertion>
                {
                    new() { Type = "status_code", Expected = "400", Operator = "equals" }
                },
                AutoGenerated = true,
                Description = $"Invalid format for path parameter {idParam.Name} should result in 400"
            });

            // Non-existing ID → 404
            counter++;
            var notFoundPathParams = BuildPathParams(endpoint);
            if (notFoundPathParams != null)
            {
                notFoundPathParams[idParam.Name] = idParam.Schema.Format == "uuid"
                    ? "00000000-0000-0000-0000-000000000000"
                    : "999999999";
            }

            tests.Add(new TestCaseDefinition
            {
                Id = $"NEG-{counter:D4}",
                Name = $"[Negative] {endpoint.Method} {endpoint.Path} - Non-existing {idParam.Name} → 404",
                Severity = "P1",
                Method = endpoint.Method,
                Path = endpoint.Path,
                CoverageCategory = "Negative",
                ExpectedStatusCodes = [404],
                PathParams = notFoundPathParams,
                Assertions = new List<TestAssertion>
                {
                    new() { Type = "status_code", Expected = "404", Operator = "equals" }
                },
                AutoGenerated = true,
                Description = $"Non-existing {idParam.Name} should result in 404 Not Found"
            });
        }

        return tests;
    }

    // ──────────────────────────────────────────────────
    // CONTRACT TESTS (P1)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateContractTests(ParsedEndpoint endpoint, ref int counter)
    {
        var tests = new List<TestCaseDefinition>();

        // Schema validation test for each success response
        foreach (var (statusCode, schema) in endpoint.Responses)
        {
            if (!statusCode.StartsWith("2")) continue;

            counter++;
            var test = new TestCaseDefinition
            {
                Id = $"CTR-{counter:D4}",
                Name = $"[Contract] {endpoint.Method} {endpoint.Path} - Response schema valid ({statusCode})",
                Severity = "P1",
                Method = endpoint.Method,
                Path = endpoint.Path,
                CoverageCategory = "Contract",
                ExpectedStatusCodes = [int.Parse(statusCode)],
                PathParams = BuildPathParams(endpoint),
                AutoGenerated = true,
                Description = $"Response must strictly match schema for {statusCode}"
            };

            if (endpoint.RequestBody != null)
                test.Payload = _payloadBuilder.BuildPayload(endpoint.RequestBody);

            // Strict schema validation
            test.Assertions.Add(new TestAssertion
            {
                Type = "schema_valid",
                Expected = "true",
                Operator = "equals"
            });

            // No additional properties (if defined)
            if (!schema.AdditionalPropertiesAllowed)
            {
                test.Assertions.Add(new TestAssertion
                {
                    Type = "no_additional_properties",
                    Expected = "true",
                    Operator = "equals"
                });
            }

            // Header existence
            test.Assertions.Add(new TestAssertion
            {
                Type = "header_exists",
                Expression = "content-type",
                Operator = "exists"
            });

            tests.Add(test);
        }

        return tests;
    }

    // ──────────────────────────────────────────────────
    // STATE-AWARE CRUD SEQUENCES (P0)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateCrudSequences(ParsedApiSpec spec, ref int counter)
    {
        var tests = new List<TestCaseDefinition>();

        // Group endpoints by resource path pattern (e.g., /users, /users/{id})
        var resourceGroups = IdentifyResourceGroups(spec.Endpoints);

        foreach (var (resource, endpoints) in resourceGroups)
        {
            var postEndpoint = endpoints.FirstOrDefault(e => e.Method == "POST");
            var getOneEndpoint = endpoints.FirstOrDefault(e => e.Method == "GET" && HasIdParam(e));
            var putEndpoint = endpoints.FirstOrDefault(e => e.Method is "PUT" or "PATCH");
            var deleteEndpoint = endpoints.FirstOrDefault(e => e.Method == "DELETE");

            // Need at least POST and GET to build a meaningful CRUD sequence
            if (postEndpoint == null || getOneEndpoint == null) continue;

            var sequenceId = $"CRUD-{resource.Replace("/", "_").TrimStart('_')}";

            // Step 1: POST (Create)
            counter++;
            var createTest = new TestCaseDefinition
            {
                Id = $"{sequenceId}-CREATE-{counter:D4}",
                Name = $"[CRUD] POST {postEndpoint.Path} - Create resource",
                Severity = "P0",
                Method = "POST",
                Path = postEndpoint.Path,
                CoverageCategory = "StateAwareCRUD",
                ExpectedStatusCodes = [200, 201],
                AutoGenerated = true,
                Description = $"Create a new {resource} resource"
            };

            if (postEndpoint.RequestBody != null)
                createTest.Payload = _payloadBuilder.BuildPayload(postEndpoint.RequestBody);

            createTest.Assertions.Add(new TestAssertion { Type = "status_code", Expected = "200,201", Operator = "in" });
            createTest.Assertions.Add(new TestAssertion { Type = "jsonpath_exists", Expression = "$.id", Operator = "exists" });
            tests.Add(createTest);

            // Step 2: GET (Read - verify creation)
            counter++;
            var readTest = new TestCaseDefinition
            {
                Id = $"{sequenceId}-READ-{counter:D4}",
                Name = $"[CRUD] GET {getOneEndpoint.Path} - Read created resource",
                Severity = "P0",
                Method = "GET",
                Path = getOneEndpoint.Path,
                CoverageCategory = "StateAwareCRUD",
                ExpectedStatusCodes = [200],
                Dependencies = new List<string> { createTest.Id },
                AutoGenerated = true,
                Description = $"Read the created {resource} resource to verify it exists"
            };
            readTest.Assertions.Add(new TestAssertion { Type = "status_code", Expected = "200", Operator = "equals" });
            tests.Add(readTest);

            // Step 3: PUT/PATCH (Update)
            if (putEndpoint != null)
            {
                counter++;
                var updateTest = new TestCaseDefinition
                {
                    Id = $"{sequenceId}-UPDATE-{counter:D4}",
                    Name = $"[CRUD] {putEndpoint.Method} {putEndpoint.Path} - Update resource",
                    Severity = "P0",
                    Method = putEndpoint.Method,
                    Path = putEndpoint.Path,
                    CoverageCategory = "StateAwareCRUD",
                    ExpectedStatusCodes = [200],
                    Dependencies = new List<string> { createTest.Id },
                    AutoGenerated = true,
                    Description = $"Update the created {resource} resource"
                };

                if (putEndpoint.RequestBody != null)
                    updateTest.Payload = _payloadBuilder.BuildPayload(putEndpoint.RequestBody);

                updateTest.Assertions.Add(new TestAssertion { Type = "status_code", Expected = "200", Operator = "equals" });
                tests.Add(updateTest);

                // Step 3b: GET again (verify update)
                counter++;
                var verifyUpdateTest = new TestCaseDefinition
                {
                    Id = $"{sequenceId}-VERIFY-{counter:D4}",
                    Name = $"[CRUD] GET {getOneEndpoint.Path} - Verify update",
                    Severity = "P0",
                    Method = "GET",
                    Path = getOneEndpoint.Path,
                    CoverageCategory = "StateAwareCRUD",
                    ExpectedStatusCodes = [200],
                    Dependencies = new List<string> { updateTest.Id },
                    AutoGenerated = true,
                    Description = $"Verify the {resource} resource was updated correctly"
                };
                verifyUpdateTest.Assertions.Add(new TestAssertion { Type = "status_code", Expected = "200", Operator = "equals" });
                tests.Add(verifyUpdateTest);
            }

            // Step 4: DELETE
            if (deleteEndpoint != null)
            {
                counter++;
                var deleteTest = new TestCaseDefinition
                {
                    Id = $"{sequenceId}-DELETE-{counter:D4}",
                    Name = $"[CRUD] DELETE {deleteEndpoint.Path} - Delete resource",
                    Severity = "P0",
                    Method = "DELETE",
                    Path = deleteEndpoint.Path,
                    CoverageCategory = "StateAwareCRUD",
                    ExpectedStatusCodes = [200, 204],
                    Dependencies = new List<string> { createTest.Id },
                    AutoGenerated = true,
                    Description = $"Delete the created {resource} resource"
                };
                deleteTest.Assertions.Add(new TestAssertion { Type = "status_code", Expected = "200,204", Operator = "in" });

                // Teardown: always attempt delete
                tests.Add(deleteTest);

                // Step 5: GET after DELETE → 404
                counter++;
                var verifyDeleteTest = new TestCaseDefinition
                {
                    Id = $"{sequenceId}-GONE-{counter:D4}",
                    Name = $"[CRUD] GET {getOneEndpoint.Path} - Verify deletion → 404",
                    Severity = "P0",
                    Method = "GET",
                    Path = getOneEndpoint.Path,
                    CoverageCategory = "StateAwareCRUD",
                    ExpectedStatusCodes = [404],
                    Dependencies = new List<string> { deleteTest.Id },
                    AutoGenerated = true,
                    Description = $"Verify the {resource} resource returns 404 after deletion"
                };
                verifyDeleteTest.Assertions.Add(new TestAssertion { Type = "status_code", Expected = "404", Operator = "equals" });
                tests.Add(verifyDeleteTest);
            }
        }

        return tests;
    }

    // ──────────────────────────────────────────────────
    // HELPERS
    // ──────────────────────────────────────────────────

    private TestCaseDefinition CreateMutationTest(
        string id, string category, string severity,
        ParsedEndpoint endpoint, MutationResult mutation)
    {
        return new TestCaseDefinition
        {
            Id = id,
            Name = $"[{category}] {endpoint.Method} {endpoint.Path} - {mutation.Description}",
            Severity = severity,
            Method = endpoint.Method,
            Path = endpoint.Path,
            Payload = mutation.MutatedPayload,
            ExpectedStatusCodes = mutation.ExpectedStatusCodes,
            CoverageCategory = category,
            PathParams = BuildPathParams(endpoint),
            Assertions = new List<TestAssertion>
            {
                new()
                {
                    Type = "status_code",
                    Expected = string.Join(",", mutation.ExpectedStatusCodes),
                    Operator = mutation.ExpectedStatusCodes.Length > 1 ? "in" : "equals"
                }
            },
            AutoGenerated = true,
            NeedsReview = false,
            Description = mutation.Description
        };
    }

    private static Dictionary<string, string>? BuildPathParams(ParsedEndpoint endpoint)
    {
        var pathParams = endpoint.Parameters.Where(p => p.In == "path").ToList();
        if (pathParams.Count == 0) return null;

        var result = new Dictionary<string, string>();
        foreach (var param in pathParams)
        {
            result[param.Name] = param.Schema.Format == "uuid"
                ? Guid.NewGuid().ToString()
                : "1";
        }
        return result;
    }

    private static int[] GetSuccessStatusCodes(ParsedEndpoint endpoint)
    {
        var codes = endpoint.Responses.Keys
            .Where(k => k.StartsWith("2"))
            .Select(k => int.TryParse(k, out var c) ? c : 0)
            .Where(c => c > 0)
            .ToArray();

        return codes.Length > 0 ? codes : endpoint.Method switch
        {
            "POST" => [200, 201],
            "PUT" or "PATCH" => [200],
            "DELETE" => [200, 204],
            _ => [200]
        };
    }

    private static bool IsIdParameter(ParsedParameter param)
    {
        var name = param.Name.ToLower();
        return name is "id" or "id" ||
               name.EndsWith("id") ||
               param.Schema.Format == "uuid" ||
               param.Schema.Format == "int64";
    }

    private static bool HasIdParam(ParsedEndpoint endpoint)
    {
        return endpoint.Parameters.Any(p => p.In == "path" && IsIdParameter(p));
    }

    private static Dictionary<string, List<ParsedEndpoint>> IdentifyResourceGroups(List<ParsedEndpoint> endpoints)
    {
        var groups = new Dictionary<string, List<ParsedEndpoint>>();

        foreach (var endpoint in endpoints)
        {
            // Extract resource name from path: /api/users/{id} → /api/users
            var resourcePath = GetResourceBasePath(endpoint.Path);
            if (string.IsNullOrEmpty(resourcePath)) continue;

            if (!groups.ContainsKey(resourcePath))
                groups[resourcePath] = new List<ParsedEndpoint>();

            groups[resourcePath].Add(endpoint);
        }

        // Only keep groups that have at least a POST and GET
        return groups.Where(g =>
            g.Value.Any(e => e.Method == "POST") &&
            g.Value.Any(e => e.Method == "GET"))
            .ToDictionary(g => g.Key, g => g.Value);
    }

    private static string GetResourceBasePath(string path)
    {
        // Remove path params: /api/users/{id}/orders/{orderId} → /api/users
        var segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        var baseSegments = new List<string>();

        foreach (var segment in segments)
        {
            if (segment.StartsWith("{")) break;
            baseSegments.Add(segment);
        }

        return baseSegments.Count > 0 ? "/" + string.Join("/", baseSegments) : string.Empty;
    }
}

