namespace LoadForge.Core.Entities;

/// <summary>
/// Represents a deterministically generated test case from OpenAPI specification
/// </summary>
public class GeneratedTestCase
{
    /// <summary>Unique identifier</summary>
    public Guid Id { get; set; }

    /// <summary>API Collection this test case belongs to</summary>
    public Guid CollectionId { get; set; }
    public ApiCollection? Collection { get; set; }

    /// <summary>Human-readable test name</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Test severity: P0 (Critical) | P1 (High) | P2 (Medium)</summary>
    public string Severity { get; set; } = "P1"; // P0|P1|P2

    /// <summary>HTTP method: GET|POST|PUT|PATCH|DELETE</summary>
    public string Method { get; set; } = "GET";

    /// <summary>API endpoint path (e.g., /api/users/{id})</summary>
    public string Path { get; set; } = string.Empty;

    /// <summary>JSON request payload (null for GET/DELETE without body)</summary>
    public string? PayloadJson { get; set; }

    /// <summary>Array of acceptable HTTP status codes (e.g., [200, 201])</summary>
    public int[] ExpectedStatusCodes { get; set; } = [200];

    /// <summary>JSON array of assertion rules to validate response</summary>
    public string? AssertionsJson { get; set; }

    /// <summary>JSON array of setup steps before test execution</summary>
    public string? SetupJson { get; set; }

    /// <summary>JSON array of teardown steps after test execution (guaranteed execution)</summary>
    public string? TeardownJson { get; set; }

    /// <summary>JSON array of test IDs this test depends on</summary>
    public string? DependenciesJson { get; set; }

    /// <summary>Whether this test was auto-generated (true) or manually created (false)</summary>
    public bool AutoGenerated { get; set; } = true;

    /// <summary>Whether this test needs human review (especially for SLM-generated tests)</summary>
    public bool NeedsReview { get; set; } = false;

    /// <summary>Test coverage category: Smoke|Validation|Boundary|Negative|Contract|StateAwareCRUD</summary>
    public string CoverageCategory { get; set; } = "Smoke";

    /// <summary>Whether test is active and should be executed</summary>
    public bool IsActive { get; set; } = true;

    /// <summary>Creation timestamp</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Last modification timestamp</summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}

