using LoadForge.TestGeneration.Generation;
using LoadForge.TestGeneration.Models;

namespace LoadForge.TestGeneration.Slm;

/// <summary>
/// Converts SLM-extracted business rules into TestCaseDefinitions.
/// 
/// ALL tests generated by this class have:
///   - needs_review: true
///   - auto_generated: true
///   - severity: P1 (conservative — human can upgrade)
///   
/// These tests cannot gate CI by default.
/// They exist as suggestions for human review.
/// </summary>
public class SlmRuleApplier
{
    private readonly ValidPayloadBuilder _payloadBuilder;
    private int _counter;

    public SlmRuleApplier(ValidPayloadBuilder? payloadBuilder = null)
    {
        _payloadBuilder = payloadBuilder ?? new ValidPayloadBuilder();
    }

    /// <summary>
    /// Generate test cases from SLM-extracted rules.
    /// Each rule generates 1-2 test cases (valid + violation).
    /// </summary>
    public List<TestCaseDefinition> GenerateTestsFromRules(
        SlmExtractionResult extraction,
        ParsedApiSpec? spec = null)
    {
        var tests = new List<TestCaseDefinition>();

        foreach (var rule in extraction.Rules)
        {
            var endpoints = extraction.ImpactedEndpoints;
            if (endpoints.Count == 0 && spec != null)
            {
                // If no endpoints specified, apply to all POST/PUT/PATCH endpoints
                endpoints = spec.Endpoints
                    .Where(e => e.Method is "POST" or "PUT" or "PATCH")
                    .Select(e => new ImpactedEndpoint { Method = e.Method, Path = e.Path })
                    .ToList();
            }

            foreach (var endpoint in endpoints)
            {
                tests.AddRange(GenerateTestsForRule(rule, endpoint));
            }
        }

        return tests;
    }

    private List<TestCaseDefinition> GenerateTestsForRule(BusinessRule rule, ImpactedEndpoint endpoint)
    {
        return rule.Type switch
        {
            AllowedRuleTypes.Comparison => GenerateComparisonTests(rule, endpoint),
            AllowedRuleTypes.ConditionalRequired => GenerateConditionalRequiredTests(rule, endpoint),
            AllowedRuleTypes.RoleRestriction => GenerateRoleRestrictionTests(rule, endpoint),
            AllowedRuleTypes.StateRestriction => GenerateStateRestrictionTests(rule, endpoint),
            AllowedRuleTypes.NumericLimit => GenerateNumericLimitTests(rule, endpoint),
            AllowedRuleTypes.FormatValidation => GenerateFormatValidationTests(rule, endpoint),
            _ => new List<TestCaseDefinition>()
        };
    }

    // ──────────────────────────────────────────────────
    // COMPARISON RULES (e.g., endDate > startDate)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateComparisonTests(BusinessRule rule, ImpactedEndpoint endpoint)
    {
        var tests = new List<TestCaseDefinition>();

        if (rule.LeftField == null) return tests;

        // Violation test: left field violates the comparison
        _counter++;
        tests.Add(CreateSlmTest(
            $"SLM-CMP-{_counter:D4}",
            endpoint,
            $"[SLM-Comparison] {endpoint.Method} {endpoint.Path} - {rule.LeftField} {InvertOperator(rule.Operator ?? ">")} {rule.RightField ?? rule.RightValue}",
            rule.Description ?? $"Comparison rule violation: {rule.LeftField} {rule.Operator} {rule.RightField ?? rule.RightValue}",
            new[] { 400, 422 }
        ));

        return tests;
    }

    // ──────────────────────────────────────────────────
    // CONDITIONAL REQUIRED (e.g., if type=premium, then tier is required)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateConditionalRequiredTests(BusinessRule rule, ImpactedEndpoint endpoint)
    {
        var tests = new List<TestCaseDefinition>();

        if (rule.ConditionField == null || rule.RequiredField == null) return tests;

        // Test: set condition but omit required field
        _counter++;
        tests.Add(CreateSlmTest(
            $"SLM-CR-{_counter:D4}",
            endpoint,
            $"[SLM-ConditionalRequired] {endpoint.Method} {endpoint.Path} - When {rule.ConditionField}={rule.ConditionValue}, {rule.RequiredField} missing → 400",
            rule.Description ?? $"When {rule.ConditionField} is {rule.ConditionValue}, field {rule.RequiredField} should be required",
            new[] { 400, 422 }
        ));

        return tests;
    }

    // ──────────────────────────────────────────────────
    // ROLE RESTRICTION (e.g., only Admin can delete)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateRoleRestrictionTests(BusinessRule rule, ImpactedEndpoint endpoint)
    {
        var tests = new List<TestCaseDefinition>();

        if (rule.Role == null) return tests;

        // Test: wrong role → 403
        _counter++;
        tests.Add(CreateSlmTest(
            $"SLM-ROLE-{_counter:D4}",
            endpoint,
            $"[SLM-RoleRestriction] {endpoint.Method} {endpoint.Path} - Non-{rule.Role} role → 403",
            rule.Description ?? $"Only {rule.Role} role should be able to access {endpoint.Method} {endpoint.Path}",
            new[] { 403 }
        ));

        return tests;
    }

    // ──────────────────────────────────────────────────
    // STATE RESTRICTION (e.g., order must be 'pending' to cancel)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateStateRestrictionTests(BusinessRule rule, ImpactedEndpoint endpoint)
    {
        var tests = new List<TestCaseDefinition>();

        if (rule.AllowedStates == null || rule.AllowedStates.Count == 0) return tests;

        // Test: resource in disallowed state → 409 or 400
        _counter++;
        tests.Add(CreateSlmTest(
            $"SLM-STATE-{_counter:D4}",
            endpoint,
            $"[SLM-StateRestriction] {endpoint.Method} {endpoint.Path} - Resource in wrong state → 409",
            rule.Description ?? $"Operation only allowed when resource is in states: {string.Join(", ", rule.AllowedStates)}",
            new[] { 400, 409 }
        ));

        return tests;
    }

    // ──────────────────────────────────────────────────
    // NUMERIC LIMIT (e.g., quantity must be <= 1000)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateNumericLimitTests(BusinessRule rule, ImpactedEndpoint endpoint)
    {
        var tests = new List<TestCaseDefinition>();

        if (rule.LeftField == null) return tests;

        _counter++;
        tests.Add(CreateSlmTest(
            $"SLM-NUM-{_counter:D4}",
            endpoint,
            $"[SLM-NumericLimit] {endpoint.Method} {endpoint.Path} - {rule.LeftField} exceeds business limit → 400",
            rule.Description ?? $"Field {rule.LeftField} must satisfy {rule.Operator} {rule.RightValue}",
            new[] { 400, 422 }
        ));

        return tests;
    }

    // ──────────────────────────────────────────────────
    // FORMAT VALIDATION (e.g., phone must match E.164)
    // ──────────────────────────────────────────────────

    private List<TestCaseDefinition> GenerateFormatValidationTests(BusinessRule rule, ImpactedEndpoint endpoint)
    {
        var tests = new List<TestCaseDefinition>();

        if (rule.LeftField == null) return tests;

        _counter++;
        tests.Add(CreateSlmTest(
            $"SLM-FMT-{_counter:D4}",
            endpoint,
            $"[SLM-FormatValidation] {endpoint.Method} {endpoint.Path} - {rule.LeftField} invalid format → 400",
            rule.Description ?? $"Field {rule.LeftField} must match format: {rule.Format}",
            new[] { 400, 422 }
        ));

        return tests;
    }

    // ──────────────────────────────────────────────────
    // HELPERS
    // ──────────────────────────────────────────────────

    private static TestCaseDefinition CreateSlmTest(
        string id, ImpactedEndpoint endpoint, string name, string description, int[] expectedStatuses)
    {
        return new TestCaseDefinition
        {
            Id = id,
            Name = name,
            Description = description,
            Severity = "P1", // Conservative — human can upgrade
            Method = endpoint.Method,
            Path = endpoint.Path,
            CoverageCategory = "SLM-Assisted",
            ExpectedStatusCodes = expectedStatuses,
            AutoGenerated = true,
            NeedsReview = true, // ALWAYS true for SLM-generated tests
            Assertions = new List<TestAssertion>
            {
                new()
                {
                    Type = "status_code",
                    Expected = string.Join(",", expectedStatuses),
                    Operator = expectedStatuses.Length > 1 ? "in" : "equals"
                }
            }
        };
    }

    private static string InvertOperator(string op)
    {
        return op switch
        {
            ">" => "<=",
            ">=" => "<",
            "<" => ">=",
            "<=" => ">",
            "==" => "!=",
            "!=" => "==",
            _ => op
        };
    }
}

