using System.Text.Json.Serialization;

namespace LoadForge.TestGeneration.Models;

/// <summary>
/// Strict test case structure as defined in the project instruction document.
/// NO DEVIATION ALLOWED.
/// </summary>
public class TestCaseDefinition
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    [JsonPropertyName("name")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("severity")]
    public string Severity { get; set; } = "P1"; // P0|P1|P2

    [JsonPropertyName("method")]
    public string Method { get; set; } = "GET"; // GET|POST|PUT|PATCH|DELETE

    [JsonPropertyName("path")]
    public string Path { get; set; } = string.Empty;

    [JsonPropertyName("payload")]
    public Dictionary<string, object?>? Payload { get; set; }

    [JsonPropertyName("headers")]
    public Dictionary<string, string>? Headers { get; set; }

    [JsonPropertyName("path_params")]
    public Dictionary<string, string>? PathParams { get; set; }

    [JsonPropertyName("query_params")]
    public Dictionary<string, string>? QueryParams { get; set; }

    [JsonPropertyName("expected_status_codes")]
    public int[] ExpectedStatusCodes { get; set; } = [200];

    [JsonPropertyName("assertions")]
    public List<TestAssertion> Assertions { get; set; } = new();

    [JsonPropertyName("setup")]
    public List<TestStep> Setup { get; set; } = new();

    [JsonPropertyName("teardown")]
    public List<TestStep> Teardown { get; set; } = new();

    [JsonPropertyName("dependencies")]
    public List<string> Dependencies { get; set; } = new();

    [JsonPropertyName("auto_generated")]
    public bool AutoGenerated { get; set; } = true;

    [JsonPropertyName("needs_review")]
    public bool NeedsReview { get; set; } = false;

    [JsonPropertyName("coverage_category")]
    public string CoverageCategory { get; set; } = "Smoke"; // Smoke|Validation|Boundary|Negative|Contract|StateAwareCRUD

    [JsonPropertyName("description")]
    public string? Description { get; set; }
}

/// <summary>
/// An assertion to validate against the response
/// </summary>
public class TestAssertion
{
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;
    // Allowed types: status_code, jsonpath_exists, jsonpath_equals, jsonpath_type,
    //                header_exists, header_equals, schema_valid, body_contains,
    //                response_time_under

    [JsonPropertyName("expression")]
    public string? Expression { get; set; }

    [JsonPropertyName("expected")]
    public string? Expected { get; set; }

    [JsonPropertyName("operator")]
    public string Operator { get; set; } = "equals";
    // Allowed: equals, not_equals, contains, greater_than, less_than, exists, not_exists
}

/// <summary>
/// A setup or teardown step (e.g., creating prerequisite data)
/// </summary>
public class TestStep
{
    [JsonPropertyName("method")]
    public string Method { get; set; } = "GET";

    [JsonPropertyName("path")]
    public string Path { get; set; } = string.Empty;

    [JsonPropertyName("payload")]
    public Dictionary<string, object?>? Payload { get; set; }

    [JsonPropertyName("capture")]
    public Dictionary<string, string>? Capture { get; set; } // variable_name -> jsonpath

    [JsonPropertyName("description")]
    public string? Description { get; set; }
}

/// <summary>
/// Configuration for test generation
/// </summary>
public class TestGenerationConfig
{
    /// <summary>Random seed for deterministic generation (reproducibility)</summary>
    public int Seed { get; set; } = 42;

    /// <summary>Generate smoke tests (P0)</summary>
    public bool GenerateSmokeTests { get; set; } = true;

    /// <summary>Generate validation tests (P1)</summary>
    public bool GenerateValidationTests { get; set; } = true;

    /// <summary>Generate boundary tests (P2)</summary>
    public bool GenerateBoundaryTests { get; set; } = true;

    /// <summary>Generate negative auth tests (P1)</summary>
    public bool GenerateNegativeTests { get; set; } = true;

    /// <summary>Generate contract/schema tests (P1)</summary>
    public bool GenerateContractTests { get; set; } = true;

    /// <summary>Generate state-aware CRUD sequences (P0)</summary>
    public bool GenerateCrudTests { get; set; } = true;

    /// <summary>Base URL to use for test paths</summary>
    public string BaseUrl { get; set; } = string.Empty;

    /// <summary>Test data prefix for unique test data (cleanup safety)</summary>
    public string TestDataPrefix { get; set; } = "loadforge_test_";
}

